(function() {
    var controllers = {};

    controllers.productCtrl = function($scope, $stateParams, $location, $rootScope) {
        $scope.pathBaseUrl = "file:\\D:\\images\\";

        $scope.product = { "_id" : { "$oid" : "54675381841baffdad6ffe23" }, "prod_id" : "0001", "prod_name" : "Nike Capri Sneakers", "price" : "2050", "discount" : "0", "inventory" : { "size" : [ { "sizeId" : "size7", "color" : [ { "colorId" : "blue", "piecesLeft" : 8 } ] }, { "sizeId" : "size8", "color" : [ { "colorId" : "blue", "piecesLeft" : 9 } ] }, { "sizeId" : "size9", "color" : [ { "colorId" : "blue", "piecesLeft" : 2 } ] }, { "sizeId" : "size11", "color" : [ { "colorId" : "blue", "piecesLeft" : 10 } ] } ] }, "Catogory" : "cat1", "Brand" : "brand1", "Prod_Desc" : "Trendy and comfy, Nike has designed these Limnos Cat sneakers that you can slip into for most casual outings and flaunt your cool attitude. With print detailing to give them a stylish touch, these laced shoes crafted in bright hues pep up your outfit. Wear them with slim jeans and printed tees or casual shirts." };

        $scope.getProductInfo = function(productId) {
            if($rootScope.gender === 'men') {
                for(var item in $scope.products) {
                    if($scope.products[item].prod_id === productId)  {
                        $scope.product = $scope.products[item];
                        break;
                    }
                }
            }
            else {
                for(var item in $scope.femaleProducts) {
                    if($scope.femaleProducts[item].prod_id === productId)  {
                        $scope.product = $scope.femaleProducts[item];
                        break;
                    }
                }
            }
            $location.path("/category/" + $stateParams.gender + "/" + $stateParams.categoryId + "/product/" + $scope.product.prod_id);
        };
        $scope.categoryName = $stateParams.categoryName;
        $rootScope.gender = $stateParams.gender;

        $scope.products = [
            { "_id" : { "$oid" : "5467c0ef841baffdad6ffe25" }, "prod_id" : "0001", "prod_name" : "Nike Capri Sneakers", "price" : "2050", "discount" : "0", "inventory" : { "size" : [ { "sizeId" : "size7", "color" : [ { "colorId" : "blue", "piecesLeft" : 8 } ] }, { "sizeId" : "size8", "color" : [ { "colorId" : "blue", "piecesLeft" : 9 } ] }, { "sizeId" : "size9", "color" : [ { "colorId" : "blue", "piecesLeft" : 2 } ] }, { "sizeId" : "size11", "color" : [ { "colorId" : "blue", "piecesLeft" : 10 } ] } ] }, "Catogory" : "cat1", "Brand" : "brand1", "Prod_Desc" : "Trendy and comfy, Nike has designed these Limnos Cat sneakers that you can slip into for most casual outings and flaunt your cool attitude. With print detailing to give them a stylish touch, these laced shoes crafted in bright hues pep up your outfit. Wear them with slim jeans and printed tees or casual shirts." },
            { "_id" : { "$oid" : "5467c0f0841baffdad6ffe26" }, "prod_id" : "0002", "prod_name" : "Nike Dewired Premium Sneakers", "price" : "3050", "discount" : "0", "inventory" : { "size" : [ { "sizeId" : "size6", "color" : [ { "colorId" : "black", "piecesLeft" : 3 } ] }, { "sizeId" : "size7", "color" : [ { "colorId" : "blue", "piecesLeft" : 8 }, { "colorId" : "black", "piecesLeft" : 3 } ] }, { "sizeId" : "size8", "color" : [ { "colorId" : "blue", "piecesLeft" : 1 }, { "colorId" : "black", "piecesLeft" : 6 } ] }, { "sizeId" : "size9", "color" : [ { "colorId" : "blue", "piecesLeft" : 2 } ] }, { "sizeId" : "size11", "color" : [ { "colorId" : "blue", "piecesLeft" : 10 }, { "colorId" : "black", "piecesLeft" : 5 } ] } ] }, "Catogory" : "cat1", "Brand" : "brand1", "Prod_Desc" : "Trendy and comfy, Nike has designed these Limnos Cat sneakers that you can slip into for most casual outings and flaunt your cool attitude. With print detailing to give them a stylish touch, these laced shoes crafted in bright hues pep up your outfit. Wear them with slim jeans and printed tees or casual shirts." },
            { "_id" : { "$oid" : "5467c0f0841baffdad6ffe27" }, "prod_id" : "0003", "prod_name" : "Puma Suede Mid Classic+ Rugged Sneakers", "price" : "1000", "discount" : "0", "inventory" : { "size" : [ { "sizeId" : "size6", "color" : [ { "colorId" : "black", "piecesLeft" : 3 } ] }, { "sizeId" : "size7", "color" : [ { "colorId" : "brown", "piecesLeft" : 8 }, { "colorId" : "black", "piecesLeft" : 3 } ] }, { "sizeId" : "size8", "color" : [ { "colorId" : "brown", "piecesLeft" : 1 }, { "colorId" : "black", "piecesLeft" : 6 } ] }, { "sizeId" : "size9", "color" : [ { "colorId" : "brown", "piecesLeft" : 2 } ] }, { "sizeId" : "size11", "color" : [ { "colorId" : "brown", "piecesLeft" : 10 }, { "colorId" : "black", "piecesLeft" : 5 } ] } ] }, "Catogory" : "cat1", "Brand" : "brand2", "Prod_Desc" : "Trendy and comfy, Nike has designed these Limnos Cat sneakers that you can slip into for most casual outings and flaunt your cool attitude. With print detailing to give them a stylish touch, these laced shoes crafted in bright hues pep up your outfit. Wear them with slim jeans and printed tees or casual shirts." },
            { "_id" : { "$oid" : "5467c0f0841baffdad6ffe28" }, "prod_id" : "0004", "prod_name" : "Puma El Ace 2 Mid PN Dp Sneakers", "price" : "1000", "discount" : "0", "inventory" : { "size" : [ { "sizeId" : "size6", "color" : [ { "colorId" : "blue", "piecesLeft" : 3 } ] }, { "sizeId" : "size7", "color" : [ { "colorId" : "black", "piecesLeft" : 8 }, { "colorId" : "blue", "piecesLeft" : 3 } ] }, { "sizeId" : "size8", "color" : [ { "colorId" : "black", "piecesLeft" : 1 }, { "colorId" : "blue", "piecesLeft" : 6 } ] }, { "sizeId" : "size9", "color" : [ { "colorId" : "black", "piecesLeft" : 2 } ] }, { "sizeId" : "size11", "color" : [ { "colorId" : "black", "piecesLeft" : 10 }, { "colorId" : "blue", "piecesLeft" : 5 } ] } ] }, "Catogory" : "cat1", "Brand" : "brand2", "Prod_Desc" : "Trendy and comfy, Nike has designed these Limnos Cat sneakers that you can slip into for most casual outings and flaunt your cool attitude. With print detailing to give them a stylish touch, these laced shoes crafted in bright hues pep up your outfit. Wear them with slim jeans and printed tees or casual shirts." },
            { "_id" : { "$oid" : "5467c0f0841baffdad6ffe29" }, "prod_id" : "0005", "prod_name" : "Reebok Classics Royal Chukka Focus Lp Sneakers", "price" : "4080", "discount" : "5", "inventory" : { "size" : [ { "sizeId" : "size6", "color" : [ { "colorId" : "black", "piecesLeft" : 3 } ] }, { "sizeId" : "size7", "color" : [ { "colorId" : "blue", "piecesLeft" : 8 }, { "colorId" : "black", "piecesLeft" : 3 } ] }, { "sizeId" : "size8", "color" : [ { "colorId" : "blue", "piecesLeft" : 1 }, { "colorId" : "black", "piecesLeft" : 6 } ] }, { "sizeId" : "size9", "color" : [ { "colorId" : "blue", "piecesLeft" : 2 } ] }, { "sizeId" : "size11", "color" : [ { "colorId" : "blue", "piecesLeft" : 10 }, { "colorId" : "black", "piecesLeft" : 5 } ] } ] }, "Catogory" : "cat1", "Brand" : "brand3", "Prod_Desc" : "Trendy and comfy, Nike has designed these Limnos Cat sneakers that you can slip into for most casual outings and flaunt your cool attitude. With print detailing to give them a stylish touch, these laced shoes crafted in bright hues pep up your outfit. Wear them with slim jeans and printed tees or casual shirts." },
            { "_id" : { "$oid" : "5467c0f0841baffdad6ffe2a" }, "prod_id" : "0006", "prod_name" : "Reebok On Court Iii Lp Canvas Shoes", "price" : "3680", "discount" : "0", "inventory" : { "size" : [ { "sizeId" : "size6", "color" : [ { "colorId" : "blue", "piecesLeft" : 3 } ] }, { "sizeId" : "size7", "color" : [ { "colorId" : "blue", "piecesLeft" : 3 } ] }, { "sizeId" : "size8", "color" : [ { "colorId" : "blue", "piecesLeft" : 6 } ] }, { "sizeId" : "size9", "color" : [ { "colorId" : "blue", "piecesLeft" : 2 } ] }, { "sizeId" : "size11", "color" : [ { "colorId" : "blue", "piecesLeft" : 5 } ] } ] }, "Catogory" : "cat1", "Brand" : "brand3", "Prod_Desc" : "Trendy and comfy, Nike has designed these Limnos Cat sneakers that you can slip into for most casual outings and flaunt your cool attitude. With print detailing to give them a stylish touch, these laced shoes crafted in bright hues pep up your outfit. Wear them with slim jeans and printed tees or casual shirts." },
            { "_id" : { "$oid" : "5467c0f0841baffdad6ffe2b" }, "prod_id" : "0007", "prod_name" : "Reebok Reverse Smash Lp Outdoors Shoes", "price" : "3080", "discount" : "5", "inventory" : { "size" : [ { "sizeId" : "size6", "color" : [ { "colorId" : "black", "piecesLeft" : 3 } ] }, { "sizeId" : "size7", "color" : [ { "colorId" : "blue", "piecesLeft" : 8 }, { "colorId" : "black", "piecesLeft" : 3 } ] }, { "sizeId" : "size8", "color" : [ { "colorId" : "blue", "piecesLeft" : 1 }, { "colorId" : "black", "piecesLeft" : 6 } ] }, { "sizeId" : "size9", "color" : [ { "colorId" : "blue", "piecesLeft" : 2 } ] }, { "sizeId" : "size11", "color" : [ { "colorId" : "blue", "piecesLeft" : 10 }, { "colorId" : "black", "piecesLeft" : 5 } ] } ] }, "Catogory" : "cat1", "Brand" : "brand3", "Prod_Desc" : "Trendy and comfy, Nike has designed these Limnos Cat sneakers that you can slip into for most casual outings and flaunt your cool attitude. With print detailing to give them a stylish touch, these laced shoes crafted in bright hues pep up your outfit. Wear them with slim jeans and printed tees or casual shirts." },
            { "_id" : { "$oid" : "5467c0f0841baffdad6ffe2c" }, "prod_id" : "0008", "prod_name" : "Reebok Royal Deck Lp Mid Ankle Sneakers", "price" : "3680", "discount" : "5", "inventory" : { "size" : [ { "sizeId" : "size6", "color" : [ { "colorId" : "brown", "piecesLeft" : 3 } ] }, { "sizeId" : "size7", "color" : [ { "colorId" : "brown", "piecesLeft" : 8 }, { "colorId" : "black", "piecesLeft" : 3 } ] }, { "sizeId" : "size8", "color" : [ { "colorId" : "black", "piecesLeft" : 1 }, { "colorId" : "brown", "piecesLeft" : 6 } ] }, { "sizeId" : "size9", "color" : [ { "colorId" : "black", "piecesLeft" : 2 } ] }, { "sizeId" : "size11", "color" : [ { "colorId" : "brown", "piecesLeft" : 10 }, { "colorId" : "black", "piecesLeft" : 5 } ] } ] }, "Catogory" : "cat1", "Brand" : "brand3", "Prod_Desc" : "Trendy and comfy, Nike has designed these Limnos Cat sneakers that you can slip into for most casual outings and flaunt your cool attitude. With print detailing to give them a stylish touch, these laced shoes crafted in bright hues pep up your outfit. Wear them with slim jeans and printed tees or casual shirts." },
            { "_id" : { "$oid" : "5467c0f0841baffdad6ffe2d" }, "prod_id" : "0009", "prod_name" : "Nike Eliminate II Running and Walking Shoes", "price" : "3680", "discount" : "5", "inventory" : { "size" : [ { "sizeId" : "size6", "color" : [ { "colorId" : "blue", "piecesLeft" : 3 } ] }, { "sizeId" : "size7", "color" : [ { "colorId" : "blue", "piecesLeft" : 8 }, { "colorId" : "black", "piecesLeft" : 3 } ] }, { "sizeId" : "size8", "color" : [ { "colorId" : "black", "piecesLeft" : 1 }, { "colorId" : "blue", "piecesLeft" : 6 } ] }, { "sizeId" : "size9", "color" : [ { "colorId" : "blue", "piecesLeft" : 2 } ] }, { "sizeId" : "size11", "color" : [ { "colorId" : "blue", "piecesLeft" : 10 }, { "colorId" : "black", "piecesLeft" : 5 } ] } ] }, "Catogory" : "cat2", "Brand" : "brand1", "Prod_Desc" : "Trendy and comfy, Nike has designed these Limnos Cat sneakers that you can slip into for most casual outings and flaunt your cool attitude. With print detailing to give them a stylish touch, these laced shoes crafted in bright hues pep up your outfit. Wear them with slim jeans and printed tees or casual shirts." },
            { "_id" : { "$oid" : "5467c0f0841baffdad6ffe2e" }, "prod_id" : "0010", "prod_name" : "Nike Flex Running Shoes", "price" : "2680", "discount" : "5", "inventory" : { "size" : [ { "sizeId" : "size6", "color" : [ { "colorId" : "black", "piecesLeft" : 3 } ] }, { "sizeId" : "size7", "color" : [ { "colorId" : "black", "piecesLeft" : 8 }, { "colorId" : "blue", "piecesLeft" : 3 } ] }, { "sizeId" : "size8", "color" : [ { "colorId" : "blue", "piecesLeft" : 1 }, { "colorId" : "black", "piecesLeft" : 6 } ] }, { "sizeId" : "size9", "color" : [ { "colorId" : "black", "piecesLeft" : 2 } ] }, { "sizeId" : "size11", "color" : [ { "colorId" : "black", "piecesLeft" : 10 }, { "colorId" : "blue", "piecesLeft" : 5 } ] } ] }, "Catogory" : "cat2", "Brand" : "brand1", "Prod_Desc" : "Trendy and comfy, Nike has designed these Limnos Cat sneakers that you can slip into for most casual outings and flaunt your cool attitude. With print detailing to give them a stylish touch, these laced shoes crafted in bright hues pep up your outfit. Wear them with slim jeans and printed tees or casual shirts." },
            { "_id" : { "$oid" : "5467c0f0841baffdad6ffe2f" }, "prod_id" : "0011", "prod_name" : "Puma Descendant Slipon Running Shoes", "price" : "2690", "discount" : "10", "inventory" : { "size" : [ { "sizeId" : "size6", "color" : [ { "colorId" : "black", "piecesLeft" : 3 } ] }, { "sizeId" : "size7", "color" : [ { "colorId" : "black", "piecesLeft" : 8 }, { "colorId" : "blue", "piecesLeft" : 3 } ] }, { "sizeId" : "size8", "color" : [ { "colorId" : "blue", "piecesLeft" : 1 }, { "colorId" : "black", "piecesLeft" : 6 } ] }, { "sizeId" : "size9", "color" : [ { "colorId" : "black", "piecesLeft" : 2 } ] }, { "sizeId" : "size11", "color" : [ { "colorId" : "black", "piecesLeft" : 10 }, { "colorId" : "blue", "piecesLeft" : 5 } ] } ] }, "Catogory" : "cat2", "Brand" : "brand2", "Prod_Desc" : "Trendy and comfy, Nike has designed these Limnos Cat sneakers that you can slip into for most casual outings and flaunt your cool attitude. With print detailing to give them a stylish touch, these laced shoes crafted in bright hues pep up your outfit. Wear them with slim jeans and printed tees or casual shirts." },
            { "_id" : { "$oid" : "5467c0f0841baffdad6ffe30" }, "prod_id" : "0012", "prod_name" : "Puma Kuris II Ind. Running Shoes", "price" : "2300", "discount" : "10", "inventory" : { "size" : [ { "sizeId" : "size6", "color" : [ { "colorId" : "black", "piecesLeft" : 3 } ] }, { "sizeId" : "size7", "color" : [ { "colorId" : "black", "piecesLeft" : 8 }, { "colorId" : "blue", "piecesLeft" : 3 } ] }, { "sizeId" : "size8", "color" : [ { "colorId" : "blue", "piecesLeft" : 1 }, { "colorId" : "black", "piecesLeft" : 6 } ] }, { "sizeId" : "size9", "color" : [ { "colorId" : "black", "piecesLeft" : 2 } ] }, { "sizeId" : "size11", "color" : [ { "colorId" : "black", "piecesLeft" : 10 }, { "colorId" : "blue", "piecesLeft" : 5 } ] } ] }, "Catogory" : "cat2", "Brand" : "brand2", "Prod_Desc" : "Trendy and comfy, Nike has designed these Limnos Cat sneakers that you can slip into for most casual outings and flaunt your cool attitude. With print detailing to give them a stylish touch, these laced shoes crafted in bright hues pep up your outfit. Wear them with slim jeans and printed tees or casual shirts." }
        ];

        $scope.femaleProducts = [
            { "_id" : { "$oid" : "5467c0f0841baffdad6ffe31" }, "prod_id" : "0013", "prod_name" : "Bata Lycra Flats", "price" : "880", "discount" : "0", "inventory" : { "size" : [ { "sizeId" : "size6", "color" : [ { "colorId" : "black", "piecesLeft" : 3 } ] }, { "sizeId" : "size7", "color" : [ { "colorId" : "black", "piecesLeft" : 3 } ] }, { "sizeId" : "size8", "color" : [ { "colorId" : "black", "piecesLeft" : 6 } ] }, { "sizeId" : "size9", "color" : [ { "colorId" : "black", "piecesLeft" : 2 } ] }, { "sizeId" : "size11", "color" : [ { "colorId" : "black", "piecesLeft" : 5 } ] } ] }, "Catogory" : "cat3", "Brand" : "brand4", "Prod_Desc" : "Trendy and comfy, Nike has designed these Limnos Cat sneakers that you can slip into for most casual outings and flaunt your cool attitude. With print detailing to give them a stylish touch, these laced shoes crafted in bright hues pep up your outfit. Wear them with slim jeans and printed tees or casual shirts." },
            { "_id" : { "$oid" : "5467c0f0841baffdad6ffe32" }, "prod_id" : "0014", "prod_name" : "Bata New Flats", "price" : "1300", "discount" : "0", "inventory" : { "size" : [ { "sizeId" : "size6", "color" : [ { "colorId" : "black", "piecesLeft" : 3 } ] }, { "sizeId" : "size7", "color" : [ { "colorId" : "black", "piecesLeft" : 8 }, { "colorId" : "brown", "piecesLeft" : 3 } ] }, { "sizeId" : "size8", "color" : [ { "colorId" : "brown", "piecesLeft" : 1 }, { "colorId" : "black", "piecesLeft" : 6 } ] }, { "sizeId" : "size9", "color" : [ { "colorId" : "black", "piecesLeft" : 2 } ] }, { "sizeId" : "size11", "color" : [ { "colorId" : "black", "piecesLeft" : 10 }, { "colorId" : "brown", "piecesLeft" : 5 } ] } ] }, "Catogory" : "cat3", "Brand" : "brand4", "Prod_Desc" : "Trendy and comfy, Nike has designed these Limnos Cat sneakers that you can slip into for most casual outings and flaunt your cool attitude. With print detailing to give them a stylish touch, these laced shoes crafted in bright hues pep up your outfit. Wear them with slim jeans and printed tees or casual shirts." },
            { "_id" : { "$oid" : "5467c0f0841baffdad6ffe33" }, "prod_id" : "0015", "prod_name" : "Bata New Flats", "price" : "1150", "discount" : "0", "inventory" : { "size" : [ { "sizeId" : "size6", "color" : [ { "colorId" : "black", "piecesLeft" : 3 } ] }, { "sizeId" : "size7", "color" : [ { "colorId" : "black", "piecesLeft" : 8 }, { "colorId" : "brown", "piecesLeft" : 3 } ] }, { "sizeId" : "size8", "color" : [ { "colorId" : "brown", "piecesLeft" : 1 }, { "colorId" : "black", "piecesLeft" : 6 } ] }, { "sizeId" : "size9", "color" : [ { "colorId" : "black", "piecesLeft" : 2 } ] }, { "sizeId" : "size11", "color" : [ { "colorId" : "black", "piecesLeft" : 10 }, { "colorId" : "brown", "piecesLeft" : 5 } ] } ] }, "Catogory" : "cat3", "Brand" : "brand5", "Prod_Desc" : "Trendy and comfy, Nike has designed these Limnos Cat sneakers that you can slip into for most casual outings and flaunt your cool attitude. With print detailing to give them a stylish touch, these laced shoes crafted in bright hues pep up your outfit. Wear them with slim jeans and printed tees or casual shirts." },
            { "_id" : { "$oid" : "5467c0f0841baffdad6ffe34" }, "prod_id" : "0016", "prod_name" : "Lavie Flats 1", "price" : "880", "discount" : "0", "inventory" : { "size" : [ { "sizeId" : "size6", "color" : [ { "colorId" : "brown", "piecesLeft" : 3 } ] }, { "sizeId" : "size7", "color" : [ { "colorId" : "brown", "piecesLeft" : 3 } ] }, { "sizeId" : "size8", "color" : [ { "colorId" : "brown", "piecesLeft" : 6 } ] }, { "sizeId" : "size9", "color" : [ { "colorId" : "brown", "piecesLeft" : 2 } ] }, { "sizeId" : "size11", "color" : [ { "colorId" : "brown", "piecesLeft" : 5 } ] } ] }, "Catogory" : "cat3", "Brand" : "brand5", "Prod_Desc" : "Trendy and comfy, Nike has designed these Limnos Cat sneakers that you can slip into for most casual outings and flaunt your cool attitude. With print detailing to give them a stylish touch, these laced shoes crafted in bright hues pep up your outfit. Wear them with slim jeans and printed tees or casual shirts." },
            { "_id" : { "$oid" : "5467c0f0841baffdad6ffe35" }, "prod_id" : "0017", "prod_name" : "Catwalk Heels", "price" : "1950", "discount" : "0", "inventory" : { "size" : [ { "sizeId" : "size6", "color" : [ { "colorId" : "black", "piecesLeft" : 3 } ] }, { "sizeId" : "size7", "color" : [ { "colorId" : "black", "piecesLeft" : 8 }, { "colorId" : "brown", "piecesLeft" : 3 } ] }, { "sizeId" : "size8", "color" : [ { "colorId" : "brown", "piecesLeft" : 1 }, { "colorId" : "black", "piecesLeft" : 6 } ] }, { "sizeId" : "size9", "color" : [ { "colorId" : "black", "piecesLeft" : 2 } ] }, { "sizeId" : "size11", "color" : [ { "colorId" : "black", "piecesLeft" : 10 }, { "colorId" : "brown", "piecesLeft" : 5 } ] } ] }, "Catogory" : "cat4", "Brand" : "brand4", "Prod_Desc" : "Trendy and comfy, Nike has designed these Limnos Cat sneakers that you can slip into for most casual outings and flaunt your cool attitude. With print detailing to give them a stylish touch, these laced shoes crafted in bright hues pep up your outfit. Wear them with slim jeans and printed tees or casual shirts." },
            { "_id" : { "$oid" : "5467c0f0841baffdad6ffe36" }, "prod_id" : "0018", "prod_name" : "Catwalk Heels 1", "price" : "1250", "discount" : "0", "inventory" : { "size" : [ { "sizeId" : "size6", "color" : [ { "colorId" : "black", "piecesLeft" : 3 } ] }, { "sizeId" : "size7", "color" : [ { "colorId" : "black", "piecesLeft" : 8 } ] }, { "sizeId" : "size8", "color" : [ { "colorId" : "black", "piecesLeft" : 6 } ] }, { "sizeId" : "size9", "color" : [ { "colorId" : "black", "piecesLeft" : 2 } ] }, { "sizeId" : "size11", "color" : [ { "colorId" : "black", "piecesLeft" : 10 } ] } ] }, "Catogory" : "cat4", "Brand" : "brand4", "Prod_Desc" : "Trendy and comfy, Nike has designed these Limnos Cat sneakers that you can slip into for most casual outings and flaunt your cool attitude. With print detailing to give them a stylish touch, these laced shoes crafted in bright hues pep up your outfit. Wear them with slim jeans and printed tees or casual shirts." },
            { "_id" : { "$oid" : "5467c0f0841baffdad6ffe37" }, "prod_id" : "0019", "prod_name" : "Lavie Heels", "price" : "700", "discount" : "0", "inventory" : { "size" : [ { "sizeId" : "size6", "color" : [ { "colorId" : "black", "piecesLeft" : 3 } ] }, { "sizeId" : "size7", "color" : [ { "colorId" : "brown", "piecesLeft" : 8 }, { "colorId" : "black", "piecesLeft" : 3 } ] }, { "sizeId" : "size8", "color" : [ { "colorId" : "brown", "piecesLeft" : 1 }, { "colorId" : "black", "piecesLeft" : 6 } ] }, { "sizeId" : "size9", "color" : [ { "colorId" : "brown", "piecesLeft" : 2 } ] }, { "sizeId" : "size11", "color" : [ { "colorId" : "brown", "piecesLeft" : 10 }, { "colorId" : "black", "piecesLeft" : 5 } ] } ] }, "Catogory" : "cat4", "Brand" : "brand5", "Prod_Desc" : "Trendy and comfy, Nike has designed these Limnos Cat sneakers that you can slip into for most casual outings and flaunt your cool attitude. With print detailing to give them a stylish touch, these laced shoes crafted in bright hues pep up your outfit. Wear them with slim jeans and printed tees or casual shirts." },
            { "_id" : { "$oid" : "5467c0f0841baffdad6ffe38" }, "prod_id" : "0020", "prod_name" : "Lavie Heels", "price" : "1800", "discount" : "0", "inventory" : { "size" : [ { "sizeId" : "size6", "color" : [ { "colorId" : "brown", "piecesLeft" : 3 } ] }, { "sizeId" : "size7", "color" : [ { "colorId" : "black", "piecesLeft" : 8 }, { "colorId" : "brown", "piecesLeft" : 3 } ] }, { "sizeId" : "size8", "color" : [ { "colorId" : "black", "piecesLeft" : 1 }, { "colorId" : "brown", "piecesLeft" : 6 } ] }, { "sizeId" : "size9", "color" : [ { "colorId" : "black", "piecesLeft" : 2 } ] }, { "sizeId" : "size11", "color" : [ { "colorId" : "black", "piecesLeft" : 10 }, { "colorId" : "brown", "piecesLeft" : 5 } ] } ] }, "Catogory" : "cat4", "Brand" : "brand5", "Prod_Desc" : "Trendy and comfy, Nike has designed these Limnos Cat sneakers that you can slip into for most casual outings and flaunt your cool attitude. With print detailing to give them a stylish touch, these laced shoes crafted in bright hues pep up your outfit. Wear them with slim jeans and printed tees or casual shirts." }
        ];

        $scope.brands = [
            { "_id" : "brand1", "brand_name" : "nike", "brand_disc" : "5" },
            { "_id" : "brand2", "brand_name" : "puma", "brand_disc" : "0" },
            { "_id" : "brand3", "brand_name" : "reebok", "brand_disc" : "0" },
            { "_id" : "brand4", "brand_name" : "nike", "brand_disc" : "5" },
            { "_id" : "brand5", "brand_name" : "puma", "brand_disc" : "0" },
            { "_id" : "brand6", "brand_name" : "reebok", "brand_disc" : "0" },
            { "_id" : "brand7", "brand_name" : "nike", "brand_disc" : "5" },
            { "_id" : "brand8", "brand_name" : "puma", "brand_disc" : "0" },
            { "_id" : "brand9", "brand_name" : "reebok", "brand_disc" : "0" },
            { "_id" : "brand10", "brand_name" : "nike", "brand_disc" : "5" },
            { "_id" : "brand12", "brand_name" : "nike", "brand_disc" : "5" },
            { "_id" : "brand13", "brand_name" : "nike", "brand_disc" : "5" },
            { "_id" : "brand14", "brand_name" : "nike", "brand_disc" : "5" },
            { "_id" : "brand15", "brand_name" : "nike", "brand_disc" : "5" },
            { "_id" : "brand16", "brand_name" : "nike", "brand_disc" : "5" },
            { "_id" : "brand17", "brand_name" : "nike", "brand_disc" : "5" },
            { "_id" : "brand18", "brand_name" : "nike", "brand_disc" : "5" }
        ];

        $scope.filterObj = {
            selectedFilterId : null,
            filtersClicked: false
        };

        $scope.colors = [
            { "_id" : "col1", "color_name" : "black", "color_hex" : "#000000" },
            { "_id" : "col2", "color_name" : "brown", "color_hex" : "#A52A2A" },
            { "_id" : "col3", "color_name" : "blue", "color_hex" : "#0000FF" }
        ];

        $scope.chooseFilterCategory = function(event) {
            $scope.filterObj.selectedFilterId = event.target.id;
        };

        $scope.applyFilters = function() {
            //Apply filters here ...
            $scope.filterObj.filtersClicked = false;
        };
    };

    controllers.productIdCtrl = function($scope, $stateParams, $rootScope) {
        $scope.products = [
            { "_id" : { "$oid" : "5467c0ef841baffdad6ffe25" }, "prod_id" : "0001", "prod_name" : "Nike Capri Sneakers", "price" : "2050", "discount" : "0", "inventory" : { "size" : [ { "sizeId" : "size7", "color" : [ { "colorId" : "blue", "piecesLeft" : 8 } ] }, { "sizeId" : "size8", "color" : [ { "colorId" : "blue", "piecesLeft" : 9 } ] }, { "sizeId" : "size9", "color" : [ { "colorId" : "blue", "piecesLeft" : 2 } ] }, { "sizeId" : "size11", "color" : [ { "colorId" : "blue", "piecesLeft" : 10 } ] } ] }, "Catogory" : "cat1", "Brand" : "brand1", "Prod_Desc" : "Trendy and comfy, Nike has designed these Limnos Cat sneakers that you can slip into for most casual outings and flaunt your cool attitude. With print detailing to give them a stylish touch, these laced shoes crafted in bright hues pep up your outfit. Wear them with slim jeans and printed tees or casual shirts." },
            { "_id" : { "$oid" : "5467c0f0841baffdad6ffe26" }, "prod_id" : "0002", "prod_name" : "Nike Dewired Premium Sneakers", "price" : "3050", "discount" : "0", "inventory" : { "size" : [ { "sizeId" : "size6", "color" : [ { "colorId" : "black", "piecesLeft" : 3 } ] }, { "sizeId" : "size7", "color" : [ { "colorId" : "blue", "piecesLeft" : 8 }, { "colorId" : "black", "piecesLeft" : 3 } ] }, { "sizeId" : "size8", "color" : [ { "colorId" : "blue", "piecesLeft" : 1 }, { "colorId" : "black", "piecesLeft" : 6 } ] }, { "sizeId" : "size9", "color" : [ { "colorId" : "blue", "piecesLeft" : 2 } ] }, { "sizeId" : "size11", "color" : [ { "colorId" : "blue", "piecesLeft" : 10 }, { "colorId" : "black", "piecesLeft" : 5 } ] } ] }, "Catogory" : "cat1", "Brand" : "brand1", "Prod_Desc" : "Trendy and comfy, Nike has designed these Limnos Cat sneakers that you can slip into for most casual outings and flaunt your cool attitude. With print detailing to give them a stylish touch, these laced shoes crafted in bright hues pep up your outfit. Wear them with slim jeans and printed tees or casual shirts." },
            { "_id" : { "$oid" : "5467c0f0841baffdad6ffe27" }, "prod_id" : "0003", "prod_name" : "Puma Suede Mid Classic+ Rugged Sneakers", "price" : "1000", "discount" : "0", "inventory" : { "size" : [ { "sizeId" : "size6", "color" : [ { "colorId" : "black", "piecesLeft" : 3 } ] }, { "sizeId" : "size7", "color" : [ { "colorId" : "brown", "piecesLeft" : 8 }, { "colorId" : "black", "piecesLeft" : 3 } ] }, { "sizeId" : "size8", "color" : [ { "colorId" : "brown", "piecesLeft" : 1 }, { "colorId" : "black", "piecesLeft" : 6 } ] }, { "sizeId" : "size9", "color" : [ { "colorId" : "brown", "piecesLeft" : 2 } ] }, { "sizeId" : "size11", "color" : [ { "colorId" : "brown", "piecesLeft" : 10 }, { "colorId" : "black", "piecesLeft" : 5 } ] } ] }, "Catogory" : "cat1", "Brand" : "brand2", "Prod_Desc" : "Trendy and comfy, Nike has designed these Limnos Cat sneakers that you can slip into for most casual outings and flaunt your cool attitude. With print detailing to give them a stylish touch, these laced shoes crafted in bright hues pep up your outfit. Wear them with slim jeans and printed tees or casual shirts." },
            { "_id" : { "$oid" : "5467c0f0841baffdad6ffe28" }, "prod_id" : "0004", "prod_name" : "Puma El Ace 2 Mid PN Dp Sneakers", "price" : "1000", "discount" : "0", "inventory" : { "size" : [ { "sizeId" : "size6", "color" : [ { "colorId" : "blue", "piecesLeft" : 3 } ] }, { "sizeId" : "size7", "color" : [ { "colorId" : "black", "piecesLeft" : 8 }, { "colorId" : "blue", "piecesLeft" : 3 } ] }, { "sizeId" : "size8", "color" : [ { "colorId" : "black", "piecesLeft" : 1 }, { "colorId" : "blue", "piecesLeft" : 6 } ] }, { "sizeId" : "size9", "color" : [ { "colorId" : "black", "piecesLeft" : 2 } ] }, { "sizeId" : "size11", "color" : [ { "colorId" : "black", "piecesLeft" : 10 }, { "colorId" : "blue", "piecesLeft" : 5 } ] } ] }, "Catogory" : "cat1", "Brand" : "brand2", "Prod_Desc" : "Trendy and comfy, Nike has designed these Limnos Cat sneakers that you can slip into for most casual outings and flaunt your cool attitude. With print detailing to give them a stylish touch, these laced shoes crafted in bright hues pep up your outfit. Wear them with slim jeans and printed tees or casual shirts." },
            { "_id" : { "$oid" : "5467c0f0841baffdad6ffe29" }, "prod_id" : "0005", "prod_name" : "Reebok Classics Royal Chukka Focus Lp Sneakers", "price" : "4080", "discount" : "5", "inventory" : { "size" : [ { "sizeId" : "size6", "color" : [ { "colorId" : "black", "piecesLeft" : 3 } ] }, { "sizeId" : "size7", "color" : [ { "colorId" : "blue", "piecesLeft" : 8 }, { "colorId" : "black", "piecesLeft" : 3 } ] }, { "sizeId" : "size8", "color" : [ { "colorId" : "blue", "piecesLeft" : 1 }, { "colorId" : "black", "piecesLeft" : 6 } ] }, { "sizeId" : "size9", "color" : [ { "colorId" : "blue", "piecesLeft" : 2 } ] }, { "sizeId" : "size11", "color" : [ { "colorId" : "blue", "piecesLeft" : 10 }, { "colorId" : "black", "piecesLeft" : 5 } ] } ] }, "Catogory" : "cat1", "Brand" : "brand3", "Prod_Desc" : "Trendy and comfy, Nike has designed these Limnos Cat sneakers that you can slip into for most casual outings and flaunt your cool attitude. With print detailing to give them a stylish touch, these laced shoes crafted in bright hues pep up your outfit. Wear them with slim jeans and printed tees or casual shirts." },
            { "_id" : { "$oid" : "5467c0f0841baffdad6ffe2a" }, "prod_id" : "0006", "prod_name" : "Reebok On Court Iii Lp Canvas Shoes", "price" : "3680", "discount" : "0", "inventory" : { "size" : [ { "sizeId" : "size6", "color" : [ { "colorId" : "blue", "piecesLeft" : 3 } ] }, { "sizeId" : "size7", "color" : [ { "colorId" : "blue", "piecesLeft" : 3 } ] }, { "sizeId" : "size8", "color" : [ { "colorId" : "blue", "piecesLeft" : 6 } ] }, { "sizeId" : "size9", "color" : [ { "colorId" : "blue", "piecesLeft" : 2 } ] }, { "sizeId" : "size11", "color" : [ { "colorId" : "blue", "piecesLeft" : 5 } ] } ] }, "Catogory" : "cat1", "Brand" : "brand3", "Prod_Desc" : "Trendy and comfy, Nike has designed these Limnos Cat sneakers that you can slip into for most casual outings and flaunt your cool attitude. With print detailing to give them a stylish touch, these laced shoes crafted in bright hues pep up your outfit. Wear them with slim jeans and printed tees or casual shirts." },
            { "_id" : { "$oid" : "5467c0f0841baffdad6ffe2b" }, "prod_id" : "0007", "prod_name" : "Reebok Reverse Smash Lp Outdoors Shoes", "price" : "3080", "discount" : "5", "inventory" : { "size" : [ { "sizeId" : "size6", "color" : [ { "colorId" : "black", "piecesLeft" : 3 } ] }, { "sizeId" : "size7", "color" : [ { "colorId" : "blue", "piecesLeft" : 8 }, { "colorId" : "black", "piecesLeft" : 3 } ] }, { "sizeId" : "size8", "color" : [ { "colorId" : "blue", "piecesLeft" : 1 }, { "colorId" : "black", "piecesLeft" : 6 } ] }, { "sizeId" : "size9", "color" : [ { "colorId" : "blue", "piecesLeft" : 2 } ] }, { "sizeId" : "size11", "color" : [ { "colorId" : "blue", "piecesLeft" : 10 }, { "colorId" : "black", "piecesLeft" : 5 } ] } ] }, "Catogory" : "cat1", "Brand" : "brand3", "Prod_Desc" : "Trendy and comfy, Nike has designed these Limnos Cat sneakers that you can slip into for most casual outings and flaunt your cool attitude. With print detailing to give them a stylish touch, these laced shoes crafted in bright hues pep up your outfit. Wear them with slim jeans and printed tees or casual shirts." },
            { "_id" : { "$oid" : "5467c0f0841baffdad6ffe2c" }, "prod_id" : "0008", "prod_name" : "Reebok Royal Deck Lp Mid Ankle Sneakers", "price" : "3680", "discount" : "5", "inventory" : { "size" : [ { "sizeId" : "size6", "color" : [ { "colorId" : "brown", "piecesLeft" : 3 } ] }, { "sizeId" : "size7", "color" : [ { "colorId" : "brown", "piecesLeft" : 8 }, { "colorId" : "black", "piecesLeft" : 3 } ] }, { "sizeId" : "size8", "color" : [ { "colorId" : "black", "piecesLeft" : 1 }, { "colorId" : "brown", "piecesLeft" : 6 } ] }, { "sizeId" : "size9", "color" : [ { "colorId" : "black", "piecesLeft" : 2 } ] }, { "sizeId" : "size11", "color" : [ { "colorId" : "brown", "piecesLeft" : 10 }, { "colorId" : "black", "piecesLeft" : 5 } ] } ] }, "Catogory" : "cat1", "Brand" : "brand3", "Prod_Desc" : "Trendy and comfy, Nike has designed these Limnos Cat sneakers that you can slip into for most casual outings and flaunt your cool attitude. With print detailing to give them a stylish touch, these laced shoes crafted in bright hues pep up your outfit. Wear them with slim jeans and printed tees or casual shirts." },
            { "_id" : { "$oid" : "5467c0f0841baffdad6ffe2d" }, "prod_id" : "0009", "prod_name" : "Nike Eliminate II Running and Walking Shoes", "price" : "3680", "discount" : "5", "inventory" : { "size" : [ { "sizeId" : "size6", "color" : [ { "colorId" : "blue", "piecesLeft" : 3 } ] }, { "sizeId" : "size7", "color" : [ { "colorId" : "blue", "piecesLeft" : 8 }, { "colorId" : "black", "piecesLeft" : 3 } ] }, { "sizeId" : "size8", "color" : [ { "colorId" : "black", "piecesLeft" : 1 }, { "colorId" : "blue", "piecesLeft" : 6 } ] }, { "sizeId" : "size9", "color" : [ { "colorId" : "blue", "piecesLeft" : 2 } ] }, { "sizeId" : "size11", "color" : [ { "colorId" : "blue", "piecesLeft" : 10 }, { "colorId" : "black", "piecesLeft" : 5 } ] } ] }, "Catogory" : "cat2", "Brand" : "brand1", "Prod_Desc" : "Trendy and comfy, Nike has designed these Limnos Cat sneakers that you can slip into for most casual outings and flaunt your cool attitude. With print detailing to give them a stylish touch, these laced shoes crafted in bright hues pep up your outfit. Wear them with slim jeans and printed tees or casual shirts." },
            { "_id" : { "$oid" : "5467c0f0841baffdad6ffe2e" }, "prod_id" : "0010", "prod_name" : "Nike Flex Running Shoes", "price" : "2680", "discount" : "5", "inventory" : { "size" : [ { "sizeId" : "size6", "color" : [ { "colorId" : "black", "piecesLeft" : 3 } ] }, { "sizeId" : "size7", "color" : [ { "colorId" : "black", "piecesLeft" : 8 }, { "colorId" : "blue", "piecesLeft" : 3 } ] }, { "sizeId" : "size8", "color" : [ { "colorId" : "blue", "piecesLeft" : 1 }, { "colorId" : "black", "piecesLeft" : 6 } ] }, { "sizeId" : "size9", "color" : [ { "colorId" : "black", "piecesLeft" : 2 } ] }, { "sizeId" : "size11", "color" : [ { "colorId" : "black", "piecesLeft" : 10 }, { "colorId" : "blue", "piecesLeft" : 5 } ] } ] }, "Catogory" : "cat2", "Brand" : "brand1", "Prod_Desc" : "Trendy and comfy, Nike has designed these Limnos Cat sneakers that you can slip into for most casual outings and flaunt your cool attitude. With print detailing to give them a stylish touch, these laced shoes crafted in bright hues pep up your outfit. Wear them with slim jeans and printed tees or casual shirts." },
            { "_id" : { "$oid" : "5467c0f0841baffdad6ffe2f" }, "prod_id" : "0011", "prod_name" : "Puma Descendant Slipon Running Shoes", "price" : "2690", "discount" : "10", "inventory" : { "size" : [ { "sizeId" : "size6", "color" : [ { "colorId" : "black", "piecesLeft" : 3 } ] }, { "sizeId" : "size7", "color" : [ { "colorId" : "black", "piecesLeft" : 8 }, { "colorId" : "blue", "piecesLeft" : 3 } ] }, { "sizeId" : "size8", "color" : [ { "colorId" : "blue", "piecesLeft" : 1 }, { "colorId" : "black", "piecesLeft" : 6 } ] }, { "sizeId" : "size9", "color" : [ { "colorId" : "black", "piecesLeft" : 2 } ] }, { "sizeId" : "size11", "color" : [ { "colorId" : "black", "piecesLeft" : 10 }, { "colorId" : "blue", "piecesLeft" : 5 } ] } ] }, "Catogory" : "cat2", "Brand" : "brand2", "Prod_Desc" : "Trendy and comfy, Nike has designed these Limnos Cat sneakers that you can slip into for most casual outings and flaunt your cool attitude. With print detailing to give them a stylish touch, these laced shoes crafted in bright hues pep up your outfit. Wear them with slim jeans and printed tees or casual shirts." },
            { "_id" : { "$oid" : "5467c0f0841baffdad6ffe30" }, "prod_id" : "0012", "prod_name" : "Puma Kuris II Ind. Running Shoes", "price" : "2300", "discount" : "10", "inventory" : { "size" : [ { "sizeId" : "size6", "color" : [ { "colorId" : "black", "piecesLeft" : 3 } ] }, { "sizeId" : "size7", "color" : [ { "colorId" : "black", "piecesLeft" : 8 }, { "colorId" : "blue", "piecesLeft" : 3 } ] }, { "sizeId" : "size8", "color" : [ { "colorId" : "blue", "piecesLeft" : 1 }, { "colorId" : "black", "piecesLeft" : 6 } ] }, { "sizeId" : "size9", "color" : [ { "colorId" : "black", "piecesLeft" : 2 } ] }, { "sizeId" : "size11", "color" : [ { "colorId" : "black", "piecesLeft" : 10 }, { "colorId" : "blue", "piecesLeft" : 5 } ] } ] }, "Catogory" : "cat2", "Brand" : "brand2", "Prod_Desc" : "Trendy and comfy, Nike has designed these Limnos Cat sneakers that you can slip into for most casual outings and flaunt your cool attitude. With print detailing to give them a stylish touch, these laced shoes crafted in bright hues pep up your outfit. Wear them with slim jeans and printed tees or casual shirts." }
        ];

        $scope.femaleProducts = [
            { "_id" : { "$oid" : "5467c0f0841baffdad6ffe31" }, "prod_id" : "0013", "prod_name" : "Bata Lycra Flats", "price" : "880", "discount" : "0", "inventory" : { "size" : [ { "sizeId" : "size6", "color" : [ { "colorId" : "black", "piecesLeft" : 3 } ] }, { "sizeId" : "size7", "color" : [ { "colorId" : "black", "piecesLeft" : 3 } ] }, { "sizeId" : "size8", "color" : [ { "colorId" : "black", "piecesLeft" : 6 } ] }, { "sizeId" : "size9", "color" : [ { "colorId" : "black", "piecesLeft" : 2 } ] }, { "sizeId" : "size11", "color" : [ { "colorId" : "black", "piecesLeft" : 5 } ] } ] }, "Catogory" : "cat3", "Brand" : "brand4", "Prod_Desc" : "Trendy and comfy, Nike has designed these Limnos Cat sneakers that you can slip into for most casual outings and flaunt your cool attitude. With print detailing to give them a stylish touch, these laced shoes crafted in bright hues pep up your outfit. Wear them with slim jeans and printed tees or casual shirts." },
            { "_id" : { "$oid" : "5467c0f0841baffdad6ffe32" }, "prod_id" : "0014", "prod_name" : "Bata New Flats", "price" : "1300", "discount" : "0", "inventory" : { "size" : [ { "sizeId" : "size6", "color" : [ { "colorId" : "black", "piecesLeft" : 3 } ] }, { "sizeId" : "size7", "color" : [ { "colorId" : "black", "piecesLeft" : 8 }, { "colorId" : "brown", "piecesLeft" : 3 } ] }, { "sizeId" : "size8", "color" : [ { "colorId" : "brown", "piecesLeft" : 1 }, { "colorId" : "black", "piecesLeft" : 6 } ] }, { "sizeId" : "size9", "color" : [ { "colorId" : "black", "piecesLeft" : 2 } ] }, { "sizeId" : "size11", "color" : [ { "colorId" : "black", "piecesLeft" : 10 }, { "colorId" : "brown", "piecesLeft" : 5 } ] } ] }, "Catogory" : "cat3", "Brand" : "brand4", "Prod_Desc" : "Trendy and comfy, Nike has designed these Limnos Cat sneakers that you can slip into for most casual outings and flaunt your cool attitude. With print detailing to give them a stylish touch, these laced shoes crafted in bright hues pep up your outfit. Wear them with slim jeans and printed tees or casual shirts." },
            { "_id" : { "$oid" : "5467c0f0841baffdad6ffe33" }, "prod_id" : "0015", "prod_name" : "Bata New Flats", "price" : "1150", "discount" : "0", "inventory" : { "size" : [ { "sizeId" : "size6", "color" : [ { "colorId" : "black", "piecesLeft" : 3 } ] }, { "sizeId" : "size7", "color" : [ { "colorId" : "black", "piecesLeft" : 8 }, { "colorId" : "brown", "piecesLeft" : 3 } ] }, { "sizeId" : "size8", "color" : [ { "colorId" : "brown", "piecesLeft" : 1 }, { "colorId" : "black", "piecesLeft" : 6 } ] }, { "sizeId" : "size9", "color" : [ { "colorId" : "black", "piecesLeft" : 2 } ] }, { "sizeId" : "size11", "color" : [ { "colorId" : "black", "piecesLeft" : 10 }, { "colorId" : "brown", "piecesLeft" : 5 } ] } ] }, "Catogory" : "cat3", "Brand" : "brand5", "Prod_Desc" : "Trendy and comfy, Nike has designed these Limnos Cat sneakers that you can slip into for most casual outings and flaunt your cool attitude. With print detailing to give them a stylish touch, these laced shoes crafted in bright hues pep up your outfit. Wear them with slim jeans and printed tees or casual shirts." },
            { "_id" : { "$oid" : "5467c0f0841baffdad6ffe34" }, "prod_id" : "0016", "prod_name" : "Lavie Flats 1", "price" : "880", "discount" : "0", "inventory" : { "size" : [ { "sizeId" : "size6", "color" : [ { "colorId" : "brown", "piecesLeft" : 3 } ] }, { "sizeId" : "size7", "color" : [ { "colorId" : "brown", "piecesLeft" : 3 } ] }, { "sizeId" : "size8", "color" : [ { "colorId" : "brown", "piecesLeft" : 6 } ] }, { "sizeId" : "size9", "color" : [ { "colorId" : "brown", "piecesLeft" : 2 } ] }, { "sizeId" : "size11", "color" : [ { "colorId" : "brown", "piecesLeft" : 5 } ] } ] }, "Catogory" : "cat3", "Brand" : "brand5", "Prod_Desc" : "Trendy and comfy, Nike has designed these Limnos Cat sneakers that you can slip into for most casual outings and flaunt your cool attitude. With print detailing to give them a stylish touch, these laced shoes crafted in bright hues pep up your outfit. Wear them with slim jeans and printed tees or casual shirts." },
            { "_id" : { "$oid" : "5467c0f0841baffdad6ffe35" }, "prod_id" : "0017", "prod_name" : "Catwalk Heels", "price" : "1950", "discount" : "0", "inventory" : { "size" : [ { "sizeId" : "size6", "color" : [ { "colorId" : "black", "piecesLeft" : 3 } ] }, { "sizeId" : "size7", "color" : [ { "colorId" : "black", "piecesLeft" : 8 }, { "colorId" : "brown", "piecesLeft" : 3 } ] }, { "sizeId" : "size8", "color" : [ { "colorId" : "brown", "piecesLeft" : 1 }, { "colorId" : "black", "piecesLeft" : 6 } ] }, { "sizeId" : "size9", "color" : [ { "colorId" : "black", "piecesLeft" : 2 } ] }, { "sizeId" : "size11", "color" : [ { "colorId" : "black", "piecesLeft" : 10 }, { "colorId" : "brown", "piecesLeft" : 5 } ] } ] }, "Catogory" : "cat4", "Brand" : "brand4", "Prod_Desc" : "Trendy and comfy, Nike has designed these Limnos Cat sneakers that you can slip into for most casual outings and flaunt your cool attitude. With print detailing to give them a stylish touch, these laced shoes crafted in bright hues pep up your outfit. Wear them with slim jeans and printed tees or casual shirts." },
            { "_id" : { "$oid" : "5467c0f0841baffdad6ffe36" }, "prod_id" : "0018", "prod_name" : "Catwalk Heels 1", "price" : "1250", "discount" : "0", "inventory" : { "size" : [ { "sizeId" : "size6", "color" : [ { "colorId" : "black", "piecesLeft" : 3 } ] }, { "sizeId" : "size7", "color" : [ { "colorId" : "black", "piecesLeft" : 8 } ] }, { "sizeId" : "size8", "color" : [ { "colorId" : "black", "piecesLeft" : 6 } ] }, { "sizeId" : "size9", "color" : [ { "colorId" : "black", "piecesLeft" : 2 } ] }, { "sizeId" : "size11", "color" : [ { "colorId" : "black", "piecesLeft" : 10 } ] } ] }, "Catogory" : "cat4", "Brand" : "brand4", "Prod_Desc" : "Trendy and comfy, Nike has designed these Limnos Cat sneakers that you can slip into for most casual outings and flaunt your cool attitude. With print detailing to give them a stylish touch, these laced shoes crafted in bright hues pep up your outfit. Wear them with slim jeans and printed tees or casual shirts." },
            { "_id" : { "$oid" : "5467c0f0841baffdad6ffe37" }, "prod_id" : "0019", "prod_name" : "Lavie Heels", "price" : "700", "discount" : "0", "inventory" : { "size" : [ { "sizeId" : "size6", "color" : [ { "colorId" : "black", "piecesLeft" : 3 } ] }, { "sizeId" : "size7", "color" : [ { "colorId" : "brown", "piecesLeft" : 8 }, { "colorId" : "black", "piecesLeft" : 3 } ] }, { "sizeId" : "size8", "color" : [ { "colorId" : "brown", "piecesLeft" : 1 }, { "colorId" : "black", "piecesLeft" : 6 } ] }, { "sizeId" : "size9", "color" : [ { "colorId" : "brown", "piecesLeft" : 2 } ] }, { "sizeId" : "size11", "color" : [ { "colorId" : "brown", "piecesLeft" : 10 }, { "colorId" : "black", "piecesLeft" : 5 } ] } ] }, "Catogory" : "cat4", "Brand" : "brand5", "Prod_Desc" : "Trendy and comfy, Nike has designed these Limnos Cat sneakers that you can slip into for most casual outings and flaunt your cool attitude. With print detailing to give them a stylish touch, these laced shoes crafted in bright hues pep up your outfit. Wear them with slim jeans and printed tees or casual shirts." },
            { "_id" : { "$oid" : "5467c0f0841baffdad6ffe38" }, "prod_id" : "0020", "prod_name" : "Lavie Heels", "price" : "1800", "discount" : "0", "inventory" : { "size" : [ { "sizeId" : "size6", "color" : [ { "colorId" : "brown", "piecesLeft" : 3 } ] }, { "sizeId" : "size7", "color" : [ { "colorId" : "black", "piecesLeft" : 8 }, { "colorId" : "brown", "piecesLeft" : 3 } ] }, { "sizeId" : "size8", "color" : [ { "colorId" : "black", "piecesLeft" : 1 }, { "colorId" : "brown", "piecesLeft" : 6 } ] }, { "sizeId" : "size9", "color" : [ { "colorId" : "black", "piecesLeft" : 2 } ] }, { "sizeId" : "size11", "color" : [ { "colorId" : "black", "piecesLeft" : 10 }, { "colorId" : "brown", "piecesLeft" : 5 } ] } ] }, "Catogory" : "cat4", "Brand" : "brand5", "Prod_Desc" : "Trendy and comfy, Nike has designed these Limnos Cat sneakers that you can slip into for most casual outings and flaunt your cool attitude. With print detailing to give them a stylish touch, these laced shoes crafted in bright hues pep up your outfit. Wear them with slim jeans and printed tees or casual shirts." }
        ];

        $rootScope.gender = $stateParams.gender;

        if($rootScope.gender === 'men') {
            for(var item in $scope.products) {
                if($scope.products[item].prod_id === $stateParams.productId)  {
                    $scope.product = $scope.products[item];
                    break;
                }
            }
        }
        else {
            for(var item in $scope.femaleProducts) {
                if($scope.femaleProducts[item].prod_id === $stateParams.productId)  {
                    $scope.product = $scope.femaleProducts[item];
                    break;
                }
            }
        }

        $scope.changeImageBanner = function(event, gender) {
            var imgUrl = "";
            if(gender==='male') {
                imgUrl = "img/site-images/gen1/" + $scope.product.Catogory + "/" +
                $scope.product.Brand + "/" + $scope.product.prod_id + "/" +
                $scope.product.inventory.size[0].color[0].colorId + "/";
            }
            else {
                imgUrl = "img/site-images/gen2/" + $scope.product.Catogory + "/" +
                $scope.product.Brand + "/" + $scope.product.prod_id + "/" +
                $scope.product.inventory.size[0].color[0].colorId + "/";
            }
            switch(event.target.id) {
                case "1":
                    imgUrl += "image1.jpeg";break;
                case "2":
                    imgUrl += "image2.jpeg";break;
                case "3":
                    imgUrl += "image3.jpeg";break;
                case "4":
                    imgUrl += "image4.jpeg";break;
            }
            angular.element("#galleryMainImage").attr("src", imgUrl);
            $scope.$apply();
        }
    };
    app.controller(controllers);
})();